server:
  port: 80
spring:
  datasource:
    url: jdbc:h2:mem:dbtest
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    schema:
    - classpath*:db/schema.sql

  jpa:
    show-sql: true
    
  h2:
    console:
      enabled: true
      path: /h2

logging:  level:    com.platenogroup: debug
    
