server:
  port: 7080

spring:
  cloud:
    gateway:
      routes: 
        - predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
          uri: "http://localhost:${server.port}"
          
#static route
#ops
management:
  endpoints:
    web:      exposure:        include:        - gateway  endpoint:    gateway:      enabled: true
     