server:
  port: 7080

logging:  level:    org.springframework.cloud.gateway: trace
    
spring:
  cloud:
    gateway:
      routes: 
        - predicates:
            - Path=/api/sample
          filters:
            - StripPrefix=2
          uri: "http://ip.tianqiapi.com/?ip=27.193.13.255,123.125.71.38)"
          
        - predicates:
            - Path=/api/sample2
          filters:
            - StripPrefix=1
          uri: "http://ip.tianqiapi.com/?ip=27.193.13.255,123.125.71.38)"
          
#static route
#ops
management:
  endpoints:
    web:      exposure:        include:        - gateway  endpoint:    gateway:      enabled: true
     