server:
  port: 7080

logging:  level:    org.springframework.cloud.gateway: trace
    
spring:
  rabbitmq:    username: javauser
    password: 123456
  cloud:
    gateway:
      routes: 
        - predicates:
            - Path=/api/sample
          filters:
            - StripPrefix=2
          uri: "http://ip.tianqiapi.com/?ip=27.193.13.255,123.125.71.38)"
          
        - predicates:
            - Path=/api/sample2
          filters:
            - StripPrefix=1
          uri: "http://ip.tianqiapi.com/?ip=27.193.13.255,123.125.71.38)"      forwarded:        enabled: false 
#redis  redis:    host: 127.0.0.1
    database: 0
    port: 6379
    password: 
    timeout: 0
    jedis:      pool:        max-idle: 8
        max-wait: 1
        max-active: 8
        min-idle: 0
#static route
#ops
management:
  endpoints:
    web:      exposure:        include:        - gateway  endpoint:    gateway:      enabled: true
     